name: sensorwave
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # State management
  flutter_bloc: ^8.1.3

  # API request
  graphql_flutter: ^5.1.2
  http: ^1.1.0
  retrofit: ^4.0.1

  # Database
  floor: ^1.4.2

  # Map
  flutter_map: ^5.0.0
  
  # MQTT
  mqtt_client: ^10.0.0

  # Utils
  equatable: ^2.0.5
  flutter_hooks: ^0.20.1
  cached_network_image: ^3.2.3
  logger: ^2.0.2

  # Service locator
  get_it: ^7.6.4




flutter:
  uses-material-design: true
